"""empty message

Revision ID: 286cf53c67b8
Revises: 
Create Date: 2024-06-26 11:27:45.826937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286cf53c67b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Brands',
    sa.Column('brand_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_logo', sa.LargeBinary(), nullable=True),
    sa.Column('brand_name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('brand_id')
    )
    op.create_table('Products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('brand', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=20), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=15), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['Products.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Comments')
    op.drop_table('User')
    op.drop_table('Products')
    op.drop_table('Brands')
    # ### end Alembic commands ###
